config/routes.rb
ClasificadosWeb::Application.routes.draw do

  get "account/index"
  devise_for :users

  namespace 'admin' do
    resources :ads do
      member do
        post 'publish'
      end
    end
    resources :ad_categories
    get 'update_cities_with_state' => 'ads#update_cities', as: 'ads_update_cities'
    get 'update_categories_with_type' => 'ads#update_categories', as: 'ads_update_categories'

    get 'cuenta' => 'account#index', as: 'my_account'
    post 'guardar_datos_cuenta' => 'account#update', as: 'update_account'
  end

  get 'anuncios/:name/:id' => 'ads#show', as: 'show_ad_details'

  get 'site/seleccionar_ciudad' => 'site#select_city', as: 'select_city'
  get 'site/establecer_ciudad/:name' => 'site#set_city', as: 'set_city'

  root 'site#index'

  

end

app/models/ad.rb
# == Schema Information
#
# Table name: ads
#
#  id             :integer          not null, primary key
#  title          :string(255)
#  text           :text
#  category_id    :integer
#  city_id        :integer
#  status_id      :integer
#  is_new         :boolean
#  price          :decimal(, )
#  published_date :datetime
#  user_id        :integer
#  type_id        :integer
#  side           :string(255)
#  views          :integer
#  created_at     :datetime
#  updated_at     :datetime
#

class Ad < ActiveRecord::Base
  before_create :set_default_values

  resourcify

  belongs_to :category, class_name: 'AdCategory'
  belongs_to :city
  belongs_to :status, class_name: 'AdStatus'
  belongs_to :type, class_name: 'AdType'
  belongs_to :user

  has_many :pictures, class_name: 'AdPicture'
  
  AD_SIDES = [SIDE_LOOKING = 'Busco', SIDE_OFFERING = 'Ofrezco']
  
  validates :side, inclusion: {in: AD_SIDES}

  # Methods for public access
  def self.recent(city_id, count=10, only_published=true)
    if only_published
      @ads = Ad.where(city_id: city_id, status: AdStatus.published).order('published_date asc').take(count)
    else
      @ads = Ad.where(city_id: city_id).order('published_date asc').take(count)
    end
  end

  def self.most_popular_by_category
    Ad.joins(:type).select('ad_types.id, count(ad_types.id) as total').
      group('ad_types.id').
      order('count(ad_types.id) desc')
  end

  # Methods for authorized users
  def self.my_ads(user, count=10)
    @ads = Ad.where(user: user).order('created_at asc').take(count)
  end

  def publish
    self.status = AdStatus.published
    self.published_date = Time.zone.now
  end

  private
  def set_default_values
    if self.published_date.nil?
      self.status = AdStatus.pending
    else
      self.status = AdStatus.published
    end
  end

end

app/models/ad_type.rb
# == Schema Information
#
# Table name: ad_types
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#

class AdType < ActiveRecord::Base
  has_many :categories, class_name: 'AdCategory', :foreign_key => 'type_id'

  def self.most_active(count=10)
    AdType.order(:name).take(count)
  end
end

app/controllers/admin/ads_controller.rb
class Admin::AdsController < Admin::ProtectedController
  before_action :set_record, only: [:show, :edit, :update, :destroy]
  before_action :fill_tables, only: [:new, :create, :edit, :update]

  def index
    @ads = Ad.all
  end

  def show
  end

  def new
    @ad = Ad.new
  end

  def create
    @ad = Ad.new(ad_params)

    if params[:city_id].nil? then
    else
      @ad.city = City.find(params[:city_id])
    end

    if params[:category_id].nil? then
    else
      @ad.category = AdCategory.where(id: params[:category_id]).first
    end

    if params[:publish] then
      @ad.published_date = Date.today
    end

    @ad.user = current_user

    respond_to do |format|
      if @ad.save
        format.html { redirect_to [:admin, @ad], notice: 'El anuncio se agregó correctamente.' }
        format.json { render action: 'show', status: :created, location: @ad }
      else
        format.html { render action: 'new' }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @cities = City.by_state(@ad.city.state)
    @categories = AdCategory.by_type(@ad.type)

    @selected_state = @ad.city.state.id
    @selected_city = @ad.city.id
    @selected_type = @ad.type.id
    @selected_category = @ad.category.id unless @ad.category.nil?
  end

  def update

    if params[:city_id].nil? then
    else
      @ad.city = City.find(params[:city_id])
    end

    if params[:category_id].nil? then
    else
      @ad.category = AdCategory.find(params[:category_id])
    end

    respond_to do |format|
      if @ad.update(ad_params)
        format.html { redirect_to [:admin, @ad], notice: 'El anuncio se modificó correctamente.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @ad.destroy
    respond_to do |format|
      format.html { redirect_to admin_ads_path }
      format.json { head :no_content }
    end
  end

  def update_cities
    state = State.find(params[:state_id])
    @cities = state.cities.map { |city| [city.name, city.id] }.insert(0, 'Seleccione la ciudad')
  end

  def update_categories
    type = AdType.find(params[:type_id])
    @categories = type.categories.map { |category| [category.name, category.id]}.insert(0, 'Seleccione una categoría')
  end

  def publish
    ad = Ad.find(params[:id])
    ad.publish
    if ad.save
      render json: '1'
    else
      render ad.errors.full_messages.to_sentence
    end
  end

  private

  def set_record
    @ad = Ad.find(params[:id])
  end

  def fill_tables
    @categories = []
    @states = State.all
    @cities = []
    @types = AdType.all
  end

  def ad_params
    params.require(:ad).permit(:title, :text, :city_id, :price, :is_new, :type_id, :side)
  end

end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  def index

  end

  def show
    @ad = Ad.find(params[:id])
  end
end

app/helpers/admin/ads_helper.rb
module Admin::AdsHelper
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/views/admin/ads/_form.html.erb
<%= form_for [:admin, ad], html: {class: "form-horizontal"} do |f| %>

<fieldset>

  <legend>Introduzca los datos del anuncio</legend>

  <div class="form-group">
    <div class="col-lg-3 col-lg-offset-2">
      <%= f.radio_button :side, 'Busco', {id: 'side_looking'} %> <label for="side_looking">Busco</label>
    </div>
    <div class="col-lg-3">
      <%= f.radio_button :side, 'Ofrezco', {id: 'side_offering'} %> <label for="side_offering">Ofrezco</label>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :title, 'Título: ', {class: 'col-lg-2 control-label'} %>
    <div class="col-lg-10">
      <%= f.text_field :title, {class: 'form-control'} %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :text, 'Texto: ', {class: 'col-lg-2 control-label'} %>
    <div class="col-lg-10">
      <%= f.text_area :text, {class: 'form-control'} %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :type_id, 'Tipo: ', {class: 'col-lg-2 control-label'} %>
    <div class="col-lg-10">
      <%= f.collection_select :type_id, @types, :id, :name, {include_blank: 'Seleccione un tipo', selected: @selected_type}, {id: 'type_select', class: 'form-control'} %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :category_id, 'Categoría: ', {class: 'col-lg-2 control-label'} %>
    <div class="col-lg-10">
      <%= collection_select nil, :category_id, @categories, :id, :name, {prompt: 'Seleccione', selected: @selected_category}, {id: 'category_select', name: 'category_id', class: 'form-control'} %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :state_id, "Estado: ", {class: 'col-lg-2 control-label'} %>
    <div class="col-lg-10">
      <%= collection_select nil, :state_id, @states, :id, :name, {include_blank: 'Seleccione un estado', selected: @selected_state}, {id: 'state_select', class: 'form-control'} %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :city_id, "Ciudad: ", {class: 'col-lg-2 control-label'} %>
    <div class="col-lg-10">
      <%= collection_select nil, :city_id, @cities, :id, :name, {include_blank: 'Seleccione una ciudad', selected: @selected_city}, {id: 'city_select', name: 'city_id', class: 'form-control'} %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :price, "Precio: ", {class: 'col-lg-2 control-label'} %>
    <div class="col-lg-10">
      <%= f.text_field :price, {class: 'form-control'} %>
    </div>
  </div>

  <div class="form-group">
    <label class="checkbox col-lg-10 col-lg-offset-2">
      <%= f.check_box :is_new %> Es nuevo?
    </label>
  </div>

  <% if ad.new_record? %>
  <div class="form-group">
    <label class="checkbox col-lg-10 col-lg-offset-2">
      <%= check_box_tag :publish %> Publicar anuncio?
    </label>
  </div>
  <% end %>

  <div class="form-group">
    <div class="col-lg-5 pull-right">
      <button id="cancelarButton" class="btn btn-default">Cancelar</button>
      <button type="submit" class="btn btn-primary">Aceptar</button>
    </div>
  </div>
</fieldset>
<% end %>

<script type="text/javascript">
  $(document).ready(function () {

    $("#cancelarButton").click(function(event) {
      event.preventDefault();
      location.href = "<%= admin_ads_path %>";
    })

    $("#state_select").change(function () {
      $.ajax({
        url: "<%= admin_ads_update_cities_path %>",
        data: {
          state_id: $("#state_select").val()
        },
        dataType: 'script'
      });
    });

    $('#type_select').change(function() {
      $.ajax({
        url: "<%= admin_ads_update_categories_path %>",
        data: {
          type_id: $('#type_select').val()
        },
        dataType: 'script'
      });
    });
  });
</script>

app/views/admin/ads/edit.html.erb
<h3>Modificar anuncio</h3>

<div class="row">
  <div class="col-lg-8">
    <div class="well">
      <%= render :partial => 'form', :locals => {ad: @ad} %>
    </div>
  </div>
</div>

app/views/admin/ads/index.html.erb
<h2>Anuncios</h2>

<p>
  <%= button_to 'Agregar anuncio', new_admin_ad_path, method: :get, class: 'btn btn-primary' %>
</p>

<table class="table table-striped table-bordered table-hover">
  <thead>
  <tr>
    <th>Título</th>
    <th>Tipo</th>
    <th>Categoría</th>
    <th>Acción</th>
    <th>Ciudad</th>
    <th>Precio</th>
    <th>Status</th>
    <th>&nbsp;</th>
  </tr>
  </thead>
  <tbody>
  <% @ads.each do |ad| %>
      <tr>
        <td>
          <%= link_to ad.title, [:admin, ad] %>
        </td>
        <td>
          <%= ad.type.name unless ad.type.nil? %>
        </td>
        <td>
          <%= ad.category.name unless ad.category.nil? %>
        </td>
        <td>
          <%= ad.side %>
        </td>
        <td>
          <%= ad.city.name unless ad.city.nil? %>
        </td>
        <td>
          <%= number_to_currency ad.price %>
        </td>
        <td>
          <%= ad.status.name unless ad.status.nil? %>
        </td>
        <td>
          <div class="row">
            <div class="pull-left col-lg-6">
              <%= button_to 'Modificar', edit_admin_ad_path(ad), method: :get, class: 'btn btn-xs btn-default' %>
            </div>
            <div class="pull-left col-lg-6">
              <%= button_to 'Eliminar', [:admin, ad], method: :delete, data: {confirm: 'Estás seguro de eliminar el anuncio?'}, class: 'btn btn-xs btn-default' %>
            </div>
          </div>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/ads/new.html.erb
<h3>Agregar anuncio</h3>

<div class="row">
  <div class="col-lg-8">
    <div class="well">
      <%= render :partial => 'form', :locals => {ad: @ad} %>
    </div>
  </div>
</div>

app/views/admin/ads/show.html.erb
<div class="container admin-ad-details">
  <div class="row">
    <h3>Anuncio</h3>
  </div>
  <div class="row">
    <div class="col-lg-8">
      <h4><%= @ad.title %></h4>
    </div>
    <div class="col-lg-4">
      Status: <span id="adStatus"><%= @ad.status.name unless @ad.status.nil? %></span>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-6">
      <%= @ad.type.name unless @ad.type.nil? %> - <%= @ad.category.name unless @ad.category.nil? %>
    </div>
    <div class="col-lg-6">
      <%= @ad.city.full_name unless @ad.city.nil? %>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-4">
      <%= @ad.side %>
    </div>
    <div class="col-lg-4">
      Precio: <%= number_to_currency @ad.price %>
    </div>
    <div class="col-lg-4">
      Es nuevo: <%= @ad.is_new ? 'Si' : 'No' %>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <%= @ad.text %>
    </div>
  </div>

  <p/>

  <div class="row">
    <button class="btn" id="editAdButton" data-link="<%= edit_admin_ad_path(@ad) %>">Editar</button>
    <% if can? :publish, @ad %>
      <button class="btn" id="publishAdButton" data-link="<%= publish_admin_ad_path(@ad) %>">Publicar</button>
    <% end %>
    <button class="btn btn-link" id="goListAdsButton" data-link="<%= admin_ads_path %>">Regresar al listado</button>
  </div>

</div>

app/views/admin/ads/update_categories.js.erb
$('#category_select').html("<%= escape_javascript(options_for_select(@categories)) %>");

app/views/admin/ads/update_cities.js.erb
$('#city_select').html("<%= escape_javascript(options_for_select(@cities)) %>");