config/routes.rb
ClasificadosWeb::Application.routes.draw do

  get "account/index"
  devise_for :users

  namespace 'admin' do
    resources :ads do
      member do
        post 'publish'
      end
    end
    resources :ad_categories
    get 'update_cities_with_state' => 'ads#update_cities', as: 'ads_update_cities'
    get 'update_categories_with_type' => 'ads#update_categories', as: 'ads_update_categories'

    get 'cuenta' => 'account#index', as: 'my_account'
    post 'guardar_datos_cuenta' => 'account#update', as: 'update_account'
  end

  get 'anuncios/:name/:id' => 'ads#show', as: 'show_ad_details'

  get 'site/seleccionar_ciudad' => 'site#select_city', as: 'select_city'
  get 'site/establecer_ciudad/:name' => 'site#set_city', as: 'set_city'

  root 'site#index'

  

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  before_action :check_city, only: [:index]

  def index
    @ads = Ad.recent(cookies[:ciudad], 10)
    @types = AdType.most_active(10)
    @categories = AdCategory.most_active(10)
  end

  def select_city
    @states = State.includes(:cities).order('states.name, cities.name').references(:cities).load
  end

  def set_city
    unless params[:name].nil?
      city = City.where(name: params[:name]).first
      cookies[:ciudad] = city.id unless city.nil?
      redirect_to root_path
    end
  end

  private
  def check_city
    if cookies[:ciudad].nil?
      redirect_to select_city_path
    end
  end
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/site/index.html.erb
<div class="row">
  <div class="col-lg-6">
    <h1>Lista de anuncios</h1>
  </div>
  <form class="form-horizontal">
    <div class="col-lg-6 search-box form-group">
      <div class="col-lg-8">
        <input type="text" class="form-control" placeholder="Escriba el texto a buscar">
      </div>
      <div class="col-lg-2">
        <button class="btn btn-primary">Buscar</button>
      </div>
      <div class="col-lg-2">
        <button class="btn btn-link btn-xs">Búsqueda avanzada</button>
      </div>
    </div>
  </form>
</div>

<div class="row">
  <div class="col-lg-10">
    <% if @ads.count == 0 %>

        <h2>No hay anuncios publicados aún.</h2>
        Deseas <%= link_to 'publicar un anuncio', new_admin_ad_path %>?

    <% else %>
        <ul class="list-group ad-list">
          <% @ads.each do |ad| %>

            <li class="list-group-item">
              <div class="row">
                <div class="col-lg-2">
                  <%= image_tag '/assets/noimage.png', size: "100x100", class: 'ad-image' %>
                </div>
                <div class="col-lg-10 ad-info">
                  <div class="row">
                    <div class="col-lg-8">
                      <h4 class="list-group-item-heading">
                        <%= link_to ad.title, show_ad_details_path(ad.title, ad.id) %>
                      </h4>
                    </div>
                    <div class="col-lg-4 pull-right ad-published-by">
                      Publicado por <%= link_to ad.user.email, root_path %>,<br/> el <%= l ad.published_date %>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-lg-12">
                      <%= truncate ad.text, length: 300, omission: '...' %>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-lg-12">
                      <%= link_to ad.type.name, root_path %> <% if not ad.category.nil? %> - <%= link_to ad.category.name, root_path %> <% end %>
                    </div>
                  </div>
                </div>

              </div>
            </li>

          <% end %>
        </ul>
    <% end %>
  </div>

  <div class="col-lg-2 sidebar-filters">
    <div class="row">
      <fieldset>
        <legend>Ver por tipos</legend>
        <ul>
          <% @types.each do |type| %>
          <li>
            <%= link_to type.name, root_path %>
          </li>
          <% end %>
          <li>
            <%= link_to 'Ver todos...', root_path %>
          </li>
        </ul>
      </fieldset>
    </div>
    <div class="row">
      <fieldset>
        <legend>Ver por categorías</legend>
        <ul>
          <% @categories.each do |category| %>
          <li>
            <%= link_to category.name, root_path %>
          </li>
          <% end %>
          <li>
            <%= link_to 'Ver todas...', root_path %>
          </li>
        </ul>
      </fieldset>
    </div>
  </div>
</div>

app/views/site/select_city.html.erb
<h1>Seleccione la ciudad de la que desea ver anuncios:</h1>

<ul>
  <% @states.each do |state| %>
  <li>
    <%= state.name %>
    <ul>
      <% state.cities.each do |city| %>
      <li>
        <%= link_to city.name, set_city_path(city.name) %>
      </li>
      <% end %>
    </ul>
  </li>
  <% end %>
</ul>