config/routes.rb
ClasificadosWeb::Application.routes.draw do

  get "account/index"
  devise_for :users

  namespace 'admin' do
    resources :ads do
      member do
        post 'publish'
      end
    end
    resources :ad_categories
    get 'update_cities_with_state' => 'ads#update_cities', as: 'ads_update_cities'
    get 'update_categories_with_type' => 'ads#update_categories', as: 'ads_update_categories'

    get 'cuenta' => 'account#index', as: 'my_account'
    post 'guardar_datos_cuenta' => 'account#update', as: 'update_account'
  end

  get 'anuncios/:name/:id' => 'ads#show', as: 'show_ad_details'

  get 'site/seleccionar_ciudad' => 'site#select_city', as: 'select_city'
  get 'site/establecer_ciudad/:name' => 'site#set_city', as: 'set_city'

  root 'site#index'

  

end

app/controllers/admin/account_controller.rb
class Admin::AccountController < Admin::ProtectedController
  def index
  	@user = current_user

    @states = State.all
    @cities = []

    if not @user.city.nil?
	    @cities = City.by_state(@user.city.state)
	    @selected_state = @user.city.state.id
	    @selected_city = @user.city.id
	  end

  end

  def update
  end
end

app/helpers/admin/account_helper.rb
module Admin::AccountHelper
end

app/views/admin/account/index.html.erb
<h1>Mis datos</h1>

<div class="row">
  <div class="col-lg-8">
    <div class="well">
      <fieldset>
        <legend>Datos generales</legend>

        <%= form_for @user, url: admin_update_account_path(@user), html: {class: 'form-horizontal'} do |f| %>

          <div class="form-group">
            <label for="email" class="col-lg-4 control-label">Correo</label>
            <div class="col-lg-8">
              <%= f.email_field :email, :autofocus => true, class: 'form-control' %>
            </div>
          </div>

          <div class="form-group">
            <label for="username" class="col-lg-4 control-label">Nombre de usuario</label>
            <div class="col-lg-8">
              <%= f.text_field :username, class: 'form-control' %>
            </div>
          </div>

          <div class="form-group">
            <label for="first_name" class="col-lg-4 control-label">Nombre</label>
            <div class="col-lg-8">
              <%= f.text_field :first_name, class: 'form-control' %>
            </div>
          </div>

          <div class="form-group">
            <label for="last_name" class="col-lg-4 control-label">Apellidos</label>
            <div class="col-lg-8">
              <%= f.text_field :last_name, class: 'form-control' %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :state_id, "Estado: ", {class: 'col-lg-4 control-label'} %>
            <div class="col-lg-8">
              <%= collection_select nil, :state_id, @states, :id, :name, {include_blank: 'Seleccione un estado', selected: @selected_state}, {id: 'state_select', class: 'form-control'} %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :city_id, "Ciudad: ", {class: 'col-lg-4 control-label'} %>
            <div class="col-lg-8">
              <%= collection_select nil, :city_id, @cities, :id, :name, {include_blank: 'Seleccione una ciudad', selected: @selected_city}, {id: 'city_select', name: 'city_id', class: 'form-control'} %>
            </div>
          </div>

          <div class="form-group">
            <div class="col-lg-5 pull-right">
              <button id="cancelarButton" class="btn btn-default">Cancelar</button>
              <button type="submit" class="btn btn-primary">Guardar datos</button>
            </div>
          </div>

        <% end %>
      </fieldset>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function () {

    $("#cancelarButton").click(function(event) {
      event.preventDefault();
      location.href = "<%= admin_ads_path %>";
    })

    $("#state_select").change(function () {
      $.ajax({
        url: "<%= admin_ads_update_cities_path %>",
        data: {
          state_id: $("#state_select").val()
        },
        dataType: 'script'
      });
    });

    $('#type_select').change(function() {
      $.ajax({
        url: "<%= admin_ads_update_categories_path %>",
        data: {
          type_id: $('#type_select').val()
        },
        dataType: 'script'
      });
    });
  });
</script>