config/routes.rb
ClasificadosWeb::Application.routes.draw do

  get "account/index"
  devise_for :users

  namespace 'admin' do
    resources :ads do
      member do
        post 'publish'
      end
    end
    resources :ad_categories
    get 'update_cities_with_state' => 'ads#update_cities', as: 'ads_update_cities'
    get 'update_categories_with_type' => 'ads#update_categories', as: 'ads_update_categories'

    get 'cuenta' => 'account#index', as: 'my_account'
    post 'guardar_datos_cuenta' => 'account#update', as: 'update_account'
  end

  get 'anuncios/:name/:id' => 'ads#show', as: 'show_ad_details'

  get 'site/seleccionar_ciudad' => 'site#select_city', as: 'select_city'
  get 'site/establecer_ciudad/:name' => 'site#set_city', as: 'set_city'

  root 'site#index'

  

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>ClasificadosWeb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>

  </head>
  <body>
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <%= link_to 'ClasificadosWeb', root_path, class: 'navbar-brand' %>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li>
              <%= link_to 'Publicar anuncio', new_admin_ad_path %>
            </li>
            <li>
              <a href="../help/">Help</a>
            </li>
            <li>
              <a href="http://news.bootswatch.com">Blog</a>
            </li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="download">Download <span class="caret"></span></a>
              <ul class="dropdown-menu" aria-labelledby="download">
                <li><a tabindex="-1" href="./bootstrap.min.css">bootstrap.min.css</a></li>
                <li><a tabindex="-1" href="./bootstrap.css">bootstrap.css</a></li>
                <li class="divider"></li>
                <li><a tabindex="-1" href="./variables.less">variables.less</a></li>
                <li><a tabindex="-1" href="./bootswatch.less">bootswatch.less</a></li>
              </ul>
            </li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <%= render partial: 'common/session' %>
          </ul>

        </div>
      </div>
    </div>


    <div class="container">

      <div class="container row main-container">
          <div class="col-lg-2">
          <%= render partial: 'admin/menu' %>
        </div>
        <div class="col-lg-10">
          <%= yield %>
        </div>
      </div>

      <footer>
        <div class="row">
          <div class="col-lg-12">

            <p>Derechos reservados 2013</p>            

          </div>
        </div>

        <div class="row current-city">
          <div class="col-lg-3 pull-right">
            <div>
              <% if current_city %>
                Ciudad actual: <%= current_city %> (<%= link_to 'Cambiar', select_city_path %>)
              <% end %>
            </div>
          </div>
        </div>
        
      </footer>
    

    </div>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>ClasificadosWeb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

  </head>
  <body>
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <%= link_to 'ClasificadosWeb', root_path, class: 'navbar-brand' %>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li>
              <%= link_to 'Publicar anuncio', new_admin_ad_path %>
            </li>
            <li>
              <a href="../help/">Ayuda</a>
            </li>
            <li>
              <a href="http://news.bootswatch.com">Blog</a>
            </li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <%= render partial: 'common/session' %>
          </ul>

        </div>
      </div>
    </div>


    <div class="container">

      <div class="container main-container">
        <%= yield %>
      </div>

      <footer>
        <div class="row">
          <div class="col-lg-12">

            <p>Derechos reservados 2013</p>            

          </div>
        </div>

        <div class="row current-city">
          <div class="col-lg-3 pull-right">
            <div>
              <% if current_city %>
                Ciudad actual: <%= current_city %> (<%= link_to 'Cambiar', select_city_path %>)
              <% end %>
            </div>
          </div>
        </div>
        
      </footer>
    

    </div>

  </body>
</html>